#!/usr/bin/env bash

# remove the default nginx configuration file
rm /etc/nginx/sites-enabled/default
#nginx to listen on port 80 for all active ipv4 ips
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start the NGINX service
service nginx restart
