#!/usr/bin/env bash
#displays bestschool 10 9 times then hi then bestchool again

count=0

while [ $count -le 10 ];
do
	if [ $count -eq 9 ];then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done 
