#!/usr/bin/env bash
#loops 10 times displaying bad luck and goodluck at the 4 and 8 itteration respectively and the rest best school

count=1

while [ $count -le 10 ]; do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done 
