#!/usr/bin/env bash
#using case study 

count=1

while [ $count -le 20 ]; do
	case $count in
		4)
			echo "$count: bad luck from China"
			;;
		9)
			echo "$count: bad luck from Japan"
			;;
		17)
			echo "$count: bad luck from Italy"
			;;
		*)
			echo "$count"
			;;
	esac
	((count++))
done
